"""Initial schema

Revision ID: 4607cab0cb52
Revises: 
Create Date: 2025-09-03 10:29:05.748515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4607cab0cb52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('lighting_score', sa.Float(), nullable=True),
    sa.Column('resolution_score', sa.Float(), nullable=True),
    sa.Column('quality_level', sa.String(length=20), nullable=True),
    sa.Column('quality_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_filename'), 'videos', ['filename'], unique=True)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('video_filename', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('frames_with_balls', sa.Integer(), nullable=True),
    sa.Column('total_ball_detections', sa.Integer(), nullable=True),
    sa.Column('average_detections_per_frame', sa.Float(), nullable=True),
    sa.Column('detection_rate', sa.Float(), nullable=True),
    sa.Column('frames_with_pose', sa.Integer(), nullable=True),
    sa.Column('pose_detection_rate', sa.Float(), nullable=True),
    sa.Column('contact_frames', sa.Integer(), nullable=True),
    sa.Column('contact_timestamps', sa.Text(), nullable=True),
    sa.Column('contact_detections', sa.Text(), nullable=True),
    sa.Column('ball_detections', sa.Text(), nullable=True),
    sa.Column('pose_detections', sa.Text(), nullable=True),
    sa.Column('annotated_video_path', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('confidence_threshold_used', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_video_filename'), 'analyses', ['video_filename'], unique=False)
    op.create_index(op.f('ix_analyses_video_id'), 'analyses', ['video_id'], unique=False)
    op.create_table('ball_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('video_timestamp', sa.Float(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=True),
    sa.Column('contact_hand', sa.String(length=10), nullable=True),
    sa.Column('stroke_type', sa.String(), nullable=True),
    sa.Column('stroke_subtype', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ball_position', sa.String(), nullable=True),
    sa.Column('player_position', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detection_source', sa.String(length=20), nullable=False),
    sa.Column('ball_area', sa.Float(), nullable=True),
    sa.Column('ball_size_factor', sa.Float(), nullable=True),
    sa.Column('racket_data', sa.String(), nullable=True),
    sa.Column('ball_bbox', sa.String(), nullable=True),
    sa.Column('ball_racket_distance', sa.Float(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ball_contacts_frame_number'), 'ball_contacts', ['frame_number'], unique=False)
    op.create_index(op.f('ix_ball_contacts_id'), 'ball_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_ball_contacts_video_id'), 'ball_contacts', ['video_id'], unique=False)
    op.create_table('ball_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('frames_with_balls', sa.Integer(), nullable=True),
    sa.Column('total_ball_detections', sa.Integer(), nullable=True),
    sa.Column('average_detections_per_frame', sa.Float(), nullable=True),
    sa.Column('detection_rate', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('model_selection_reason', sa.String(), nullable=True),
    sa.Column('detection_data', sa.Text(), nullable=True),
    sa.Column('confidence_scores', sa.Text(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('frame_processing_rate', sa.Float(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('max_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ball_detections_id'), 'ball_detections', ['id'], unique=False)
    op.create_index(op.f('ix_ball_detections_video_id'), 'ball_detections', ['video_id'], unique=False)
    op.create_table('pose_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('frames_with_poses', sa.Integer(), nullable=True),
    sa.Column('total_pose_detections', sa.Integer(), nullable=True),
    sa.Column('detection_rate', sa.Float(), nullable=True),
    sa.Column('average_pose_confidence', sa.Float(), nullable=True),
    sa.Column('min_pose_confidence', sa.Float(), nullable=True),
    sa.Column('max_pose_confidence', sa.Float(), nullable=True),
    sa.Column('pose_stability_score', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('detection_threshold', sa.Float(), nullable=False),
    sa.Column('pose_data', sa.Text(), nullable=True),
    sa.Column('visibility_scores', sa.Text(), nullable=True),
    sa.Column('confidence_scores', sa.Text(), nullable=True),
    sa.Column('annotated_video_path', sa.String(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('frame_processing_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pose_detections_id'), 'pose_detections', ['id'], unique=False)
    op.create_index(op.f('ix_pose_detections_video_id'), 'pose_detections', ['video_id'], unique=False)
    op.create_table('video_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('annotated_video_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('pose_detection_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('frames_annotated', sa.Integer(), nullable=True),
    sa.Column('annotation_style', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['pose_detection_id'], ['pose_detections.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_annotations_id'), 'video_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_video_annotations_video_id'), 'video_annotations', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_annotations_video_id'), table_name='video_annotations')
    op.drop_index(op.f('ix_video_annotations_id'), table_name='video_annotations')
    op.drop_table('video_annotations')
    op.drop_index(op.f('ix_pose_detections_video_id'), table_name='pose_detections')
    op.drop_index(op.f('ix_pose_detections_id'), table_name='pose_detections')
    op.drop_table('pose_detections')
    op.drop_index(op.f('ix_ball_detections_video_id'), table_name='ball_detections')
    op.drop_index(op.f('ix_ball_detections_id'), table_name='ball_detections')
    op.drop_table('ball_detections')
    op.drop_index(op.f('ix_ball_contacts_video_id'), table_name='ball_contacts')
    op.drop_index(op.f('ix_ball_contacts_id'), table_name='ball_contacts')
    op.drop_index(op.f('ix_ball_contacts_frame_number'), table_name='ball_contacts')
    op.drop_table('ball_contacts')
    op.drop_index(op.f('ix_analyses_video_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_video_filename'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_filename'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
