"""Add Player model and player_id to BallContact

Revision ID: 4b5bac20565b
Revises: f564d88a6842
Create Date: 2025-09-10 19:00:55.495044

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b5bac20565b"
down_revision: Union[str, Sequence[str], None] = "f564d88a6842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("dominant_hand", sa.String(length=10), nullable=False),
        sa.Column("backhand_style", sa.String(length=20), nullable=False),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=False)
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=False)

    # Use batch operations for SQLite
    with op.batch_alter_table("ball_contacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("player_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f("ix_ball_contacts_player_id"), ["player_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_ball_contacts_player_id",
            "players",
            ["player_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite
    with op.batch_alter_table("ball_contacts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ball_contacts_player_id", type_="foreignkey")
        batch_op.drop_index(op.f("ix_ball_contacts_player_id"))
        batch_op.drop_column("player_id")

    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
