"""rename_frame_identification_source_to_detection_source

Revision ID: 5c0f78d9bd09
Revises: cf1fbed9706e
Create Date: 2025-09-01 09:22:30.516100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0f78d9bd09'
down_revision: Union[str, Sequence[str], None] = 'cf1fbed9706e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ball_contacts', sa.Column('detection_source', sa.String(length=20), nullable=False))
    op.drop_column('ball_contacts', 'frame_identification_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ball_contacts', sa.Column('frame_identification_source', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('ball_contacts', 'detection_source')
    # ### end Alembic commands ###
