"""Add pose detection fields to analysis model

Revision ID: 63c79de0875a
Revises: 
Create Date: 2025-08-10 09:46:15.054990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c79de0875a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('frames_with_pose', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('pose_detection_rate', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('pose_detections', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('annotated_video_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'annotated_video_path')
    op.drop_column('analyses', 'pose_detections')
    op.drop_column('analyses', 'pose_detection_rate')
    op.drop_column('analyses', 'frames_with_pose')
    # ### end Alembic commands ###
