"""add_ball_contact_detection_fields

Revision ID: 864f3843d8c3
Revises: ecaf51c7eb6d
Create Date: 2025-08-21 08:42:09.771546

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "864f3843d8c3"
down_revision: Union[str, Sequence[str], None] = "ecaf51c7eb6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analyses", sa.Column("contact_frames", sa.Integer(), nullable=True))
    op.add_column("analyses", sa.Column("contact_timestamps", sa.Text(), nullable=True))
    op.add_column("analyses", sa.Column("contact_detections", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "contact_detections")
    op.drop_column("analyses", "contact_timestamps")
    op.drop_column("analyses", "contact_frames")
    # ### end Alembic commands ###
