"""make backhand_style nullable

Revision ID: 943e05c001f6
Revises: 4b5bac20565b
Create Date: 2025-09-11 09:16:06.663056

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "943e05c001f6"
down_revision: Union[str, Sequence[str], None] = "4b5bac20565b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column(
            "backhand_style", existing_type=sa.VARCHAR(length=20), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.alter_column(
            "backhand_style", existing_type=sa.VARCHAR(length=20), nullable=False
        )
    # ### end Alembic commands ###
