"""add_ball_detections_table

Revision ID: aae3a81f8245
Revises: f292278d84cf
Create Date: 2025-09-02 22:23:34.942071

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aae3a81f8245'
down_revision: Union[str, Sequence[str], None] = 'f292278d84cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ball_detections_id'), table_name='ball_detections')
    op.drop_index(op.f('ix_ball_detections_video_id'), table_name='ball_detections')
    op.drop_table('ball_detections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ball_detections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('total_frames', sa.INTEGER(), nullable=False),
    sa.Column('frames_with_balls', sa.INTEGER(), nullable=True),
    sa.Column('total_ball_detections', sa.INTEGER(), nullable=True),
    sa.Column('average_detections_per_frame', sa.FLOAT(), nullable=True),
    sa.Column('detection_rate', sa.FLOAT(), nullable=True),
    sa.Column('model_used', sa.VARCHAR(), nullable=False),
    sa.Column('confidence_threshold', sa.FLOAT(), nullable=False),
    sa.Column('model_selection_reason', sa.VARCHAR(), nullable=True),
    sa.Column('detection_data', sa.TEXT(), nullable=True),
    sa.Column('confidence_scores', sa.TEXT(), nullable=True),
    sa.Column('processing_time_seconds', sa.FLOAT(), nullable=False),
    sa.Column('frame_processing_rate', sa.FLOAT(), nullable=True),
    sa.Column('average_confidence', sa.FLOAT(), nullable=True),
    sa.Column('min_confidence', sa.FLOAT(), nullable=True),
    sa.Column('max_confidence', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ball_detections_video_id'), 'ball_detections', ['video_id'], unique=False)
    op.create_index(op.f('ix_ball_detections_id'), 'ball_detections', ['id'], unique=False)
    # ### end Alembic commands ###
