"""add_transcoding_fields_to_video

Revision ID: add_transcoding_fields
Revises: e9078981fbf0
Create Date: 2026-02-04 15:15:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
# NOTE: This revision ID should be generated by alembic. Update before running migration.
revision: str = "add_transcoding_fields"
down_revision: Union[str, Sequence[str], None] = (
    "e9078981fbf0"  # Latest existing migration
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add transcoding metadata fields to videos table."""
    op.add_column(
        "videos",
        sa.Column(
            "is_transcoded",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "videos", sa.Column("original_file_size", sa.Integer(), nullable=True)
    )


def downgrade() -> None:
    """Remove transcoding metadata fields from videos table."""
    op.drop_column("videos", "original_file_size")
    op.drop_column("videos", "is_transcoded")
