"""add_stage_tracking_to_video_jobs

Revision ID: add_stage_tracking
Revises: add_detection_mode
Create Date: 2026-02-04 15:35:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
# NOTE: This revision ID should be generated by alembic. Update before running migration.
revision: str = "add_stage_tracking"
down_revision: Union[str, Sequence[str], None] = "add_detection_mode"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add stage tracking fields to video_jobs table."""
    op.add_column("video_jobs", sa.Column("stage", sa.String(length=50), nullable=True))
    op.add_column(
        "video_jobs",
        sa.Column("progress_percent", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "video_jobs", sa.Column("serve_windows_found", sa.Integer(), nullable=True)
    )


def downgrade() -> None:
    """Remove stage tracking fields from video_jobs table."""
    op.drop_column("video_jobs", "serve_windows_found")
    op.drop_column("video_jobs", "progress_percent")
    op.drop_column("video_jobs", "stage")
