"""add_detection_mode_to_pose_detections

Revision ID: add_detection_mode
Revises: add_transcoding_fields
Create Date: 2026-02-04 15:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
# NOTE: This revision ID should be generated by alembic. Update before running migration.
revision: str = "add_detection_mode"
down_revision: Union[str, Sequence[str], None] = "add_transcoding_fields"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add detection_mode and time_windows fields to pose_detections table."""
    op.add_column(
        "pose_detections",
        sa.Column(
            "detection_mode",
            sa.String(length=20),
            nullable=False,
            server_default="full",
        ),
    )
    op.add_column(
        "pose_detections", sa.Column("time_windows", sa.Text(), nullable=True)
    )


def downgrade() -> None:
    """Remove detection_mode and time_windows fields from pose_detections table."""
    op.drop_column("pose_detections", "time_windows")
    op.drop_column("pose_detections", "detection_mode")
