"""add_video_player_junction_table

Revision ID: b9a1f08c35d3
Revises: 943e05c001f6
Create Date: 2025-09-11 12:18:25.986711

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b9a1f08c35d3"
down_revision: Union[str, Sequence[str], None] = "943e05c001f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # VideoPlayer table was already created, foreign key constraint already exists
    # No additional changes needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes to revert
    pass
    # ### end Alembic commands ###
