"""add contact_source to serve_windows

Revision ID: be238e4d58d4
Revises: a1b2c3d4e5f6
Create Date: 2026-02-23 16:48:29.920956

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be238e4d58d4"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add contact_source column to serve_windows.

    contact_source tracks how contact_timestamp was set:
      - "manual": user explicitly provided a contact timestamp via the API
      - "auto": ball detection pipeline (YOLO + ByteTrack) or lazy fallback set it
      - NULL: rows created before this column was introduced (treated as "manual" in
              phase_segmentation.py for backwards compatibility)
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "serve_windows",
        sa.Column("contact_source", sa.String(length=10), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("serve_windows", "contact_source")
    # ### end Alembic commands ###
