"""add_ball_contacts_table

Revision ID: cf1fbed9706e
Revises: 864f3843d8c3
Create Date: 2025-08-31 21:31:35.668152

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "cf1fbed9706e"
down_revision: Union[str, Sequence[str], None] = "864f3843d8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
