"""add_session_metadata_to_videos

Revision ID: e585518be299
Revises: d1f0ec4cf292
Create Date: 2026-01-25 11:11:12.693467

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e585518be299"
down_revision: Union[str, Sequence[str], None] = "d1f0ec4cf292"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_columns(table_name: str) -> set[str]:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if table_name not in inspector.get_table_names():
        return set()
    return {column["name"] for column in inspector.get_columns(table_name)}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "serve_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("start_timestamp", sa.Float(), nullable=False),
        sa.Column("end_timestamp", sa.Float(), nullable=False),
        sa.Column("contact_timestamp", sa.Float(), nullable=True),
        sa.Column("elbow_angle_at_contact", sa.Float(), nullable=True),
        sa.Column("court_side", sa.String(length=10), nullable=True),
        sa.Column("serve_number", sa.Integer(), nullable=True),
        sa.Column("serve_subtype", sa.String(length=20), nullable=True),
        sa.Column("in_out", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_serve_attempts_id"), "serve_attempts", ["id"], unique=False
    )
    op.create_index(
        "ix_serve_attempts_player_created",
        "serve_attempts",
        ["player_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_serve_attempts_player_id"),
        "serve_attempts",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        "ix_serve_attempts_user_court_created",
        "serve_attempts",
        ["user_id", "court_side", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_serve_attempts_user_created",
        "serve_attempts",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_serve_attempts_user_id"), "serve_attempts", ["user_id"], unique=False
    )
    op.create_index(
        "ix_serve_attempts_user_player_created",
        "serve_attempts",
        ["user_id", "player_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_serve_attempts_video_id"), "serve_attempts", ["video_id"], unique=False
    )
    op.create_index(
        "ix_serve_attempts_video_start",
        "serve_attempts",
        ["video_id", "start_timestamp"],
        unique=False,
    )
    ball_contact_columns = _get_columns("ball_contacts")
    if "working_window_end" in ball_contact_columns:
        op.drop_column("ball_contacts", "working_window_end")
    if "working_window_start" in ball_contact_columns:
        op.drop_column("ball_contacts", "working_window_start")
    if "rotation_metrics" in ball_contact_columns:
        op.drop_column("ball_contacts", "rotation_metrics")
    op.drop_index(op.f("idx_players_user_id"), table_name="players")
    op.create_index(op.f("ix_players_user_id"), "players", ["user_id"], unique=False)
    op.drop_column("players", "height")
    op.add_column(
        "videos", sa.Column("session_type", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "videos", sa.Column("camera_angle", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "videos", sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("idx_videos_user_id"), table_name="videos")
    op.create_index(op.f("ix_videos_user_id"), "videos", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_user_id"), table_name="videos")
    op.create_index(op.f("idx_videos_user_id"), "videos", ["user_id"], unique=False)
    op.drop_column("videos", "recorded_at")
    op.drop_column("videos", "camera_angle")
    op.drop_column("videos", "session_type")
    op.add_column("players", sa.Column("height", sa.FLOAT(), nullable=True))
    op.drop_index(op.f("ix_players_user_id"), table_name="players")
    op.create_index(op.f("idx_players_user_id"), "players", ["user_id"], unique=False)
    ball_contact_columns = _get_columns("ball_contacts")
    if "rotation_metrics" not in ball_contact_columns:
        op.add_column(
            "ball_contacts", sa.Column("rotation_metrics", sa.TEXT(), nullable=True)
        )
    if "working_window_start" not in ball_contact_columns:
        op.add_column(
            "ball_contacts",
            sa.Column("working_window_start", sa.FLOAT(), nullable=True),
        )
    if "working_window_end" not in ball_contact_columns:
        op.add_column(
            "ball_contacts",
            sa.Column("working_window_end", sa.FLOAT(), nullable=True),
        )
    op.drop_index("ix_serve_attempts_video_start", table_name="serve_attempts")
    op.drop_index(op.f("ix_serve_attempts_video_id"), table_name="serve_attempts")
    op.drop_index("ix_serve_attempts_user_player_created", table_name="serve_attempts")
    op.drop_index(op.f("ix_serve_attempts_user_id"), table_name="serve_attempts")
    op.drop_index("ix_serve_attempts_user_created", table_name="serve_attempts")
    op.drop_index("ix_serve_attempts_user_court_created", table_name="serve_attempts")
    op.drop_index(op.f("ix_serve_attempts_player_id"), table_name="serve_attempts")
    op.drop_index("ix_serve_attempts_player_created", table_name="serve_attempts")
    op.drop_index(op.f("ix_serve_attempts_id"), table_name="serve_attempts")
    op.drop_table("serve_attempts")
    # ### end Alembic commands ###
