"""Add elbow_angle to ball_contacts table

Revision ID: f564d88a6842
Revises: 8809c3660b6f
Create Date: 2025-09-04 23:44:27.076629

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f564d88a6842"
down_revision: Union[str, Sequence[str], None] = "8809c3660b6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ball_contacts", sa.Column("elbow_angle", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ball_contacts", "elbow_angle")
    # ### end Alembic commands ###
