"""add_video_title_and_notes

Revision ID: f5fdd0df2ff5
Revises: 2cf2e7b95cd1
Create Date: 2026-02-24 10:12:50.306608

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5fdd0df2ff5"
down_revision: Union[str, Sequence[str], None] = "2cf2e7b95cd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("title", sa.String(length=200), nullable=True))
    op.add_column("videos", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "notes")
    op.drop_column("videos", "title")
    # ### end Alembic commands ###
